# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 533a20a639ed3e8afdac461926aaa1f6dbb753bff6304147458f76377da52f31c7a1dccde964c57dcf7ba6120ffc2e4a98221b4428c1d2a99b8c825575e4ca23

test:
  secret_key_base: 12b10bd2b533ca6219c2a9fa79ae2583b6b42c3bf6ab2f3ade4e1b6df872fc96b65477056129284832917d397f725f18508cd81837f9c39b1b7ea32d77d38e84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
